redis-ha:
  persistentVolume:
    enabled: false
  redis:
    masterGroupName: argocd
    config:
      save: "\"\""
  haproxy:
    enabled: true
    image:
      tag: 2.6.14-alpine
    containerSecurityContext: null
    timeout:
      server: 6m
      client: 6m
    checkInterval: 3s
    metrics:
      enabled: true
  image:
<<<<<<< HEAD
    tag: 7.0.14-alpine
=======
    tag: 7.0.5-alpine
>>>>>>> ac0fce6b6 (Inital commint - Argo CD v2.5.4 release version)
  containerSecurityContext: null
